services:
  app:
    networks:
      - magpie_shared

  worker:
    networks:
      - magpie_shared

  caddy_edge:
    networks:
      - magpie_shared

networks:
  magpie_shared:
    external: true
    name: ${MAGPIE_DOCKER_NETWORK:-app-shared}
