#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# shellcheck source=scripts/lib/module_selection.sh
source "$ROOT_DIR/scripts/lib/module_selection.sh"
# shellcheck source=scripts/lib/deploy_simplify.sh
source "$ROOT_DIR/scripts/lib/deploy_simplify.sh"

OUTPUT_PATH="$ROOT_DIR/.env.production"
PRIMARY_DOMAIN=""
ACME_EMAIL=""
MODULES="chat,social,nerve,atomine"
PROFILES="caddy"
DEPLOYMENT_PRESET="simple-web"
ADMIN_ACCESS=""
TLS_MODE="caddy-auto"
PUBLIC_DNS_BIND_IP=""
MODULES_SPECIFIED=0
PROFILES_SPECIFIED=0
FORCE=0

usage() {
  cat <<'EOF'
Usage: scripts/deploy/generate_env.sh --domain example.com --email admin@example.com [options]

Creates a minimal .env.production for first-run Docker self-hosting.

Options:
  --domain DOMAIN       Primary domain for the instance.
  --email EMAIL         ACME account email for Caddy-managed TLS.
  --preset NAME         simple-web, web-mail, web-mail-dns, or full-stack.
                        Default: simple-web
  --admin-access MODE   public, netbird, or disabled. Defaults from preset.
  --tls-mode MODE       caddy-auto, external-wildcard, or letsencrypt-dns.
                        Default: caddy-auto
  --public-dns-ip IP    Public IP for authoritative DNS bind derivation.
  --modules LIST        Enabled modules. Overrides preset modules.
  --profiles LIST       Docker profiles separated by spaces. Overrides preset profiles.
  --output PATH         Env file path. Default: .env.production
  --force               Overwrite an existing output file.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      PRIMARY_DOMAIN="$2"
      shift 2
      ;;
    --email)
      ACME_EMAIL="$2"
      shift 2
      ;;
    --preset)
      DEPLOYMENT_PRESET="$2"
      shift 2
      ;;
    --admin-access)
      ADMIN_ACCESS="$2"
      shift 2
      ;;
    --tls-mode)
      TLS_MODE="$2"
      shift 2
      ;;
    --public-dns-ip)
      PUBLIC_DNS_BIND_IP="$2"
      shift 2
      ;;
    --modules)
      MODULES="$2"
      MODULES_SPECIFIED=1
      shift 2
      ;;
    --profiles)
      PROFILES="$2"
      PROFILES_SPECIFIED=1
      shift 2
      ;;
    --output)
      OUTPUT_PATH="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    echo "Error: openssl is required to generate deployment secrets securely." >&2
    exit 1
  fi
}

validate_value() {
  local label="$1"
  local value="$2"
  local pattern="$3"

  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* || ! "$value" =~ $pattern ]]; then
    echo "Error: invalid $label: $value" >&2
    exit 1
  fi
}

if [[ -z "$PRIMARY_DOMAIN" || -z "$ACME_EMAIL" ]]; then
  usage >&2
  exit 1
fi

validate_value "domain" "$PRIMARY_DOMAIN" '^[A-Za-z0-9.-]+$'
validate_value "email" "$ACME_EMAIL" '^[^[:space:]@]+@[^[:space:]@]+$'
validate_value "module list" "$MODULES" '^[A-Za-z0-9_, -]+$'
validate_value "profile list" "$PROFILES" '^[A-Za-z0-9_ -]+$'
validate_value "preset" "$DEPLOYMENT_PRESET" '^[a-z-]+$'
validate_value "admin access" "${ADMIN_ACCESS:-public}" '^(public|netbird|disabled)$'
validate_value "TLS mode" "$TLS_MODE" '^(caddy-auto|external-wildcard|letsencrypt-dns)$'

if [[ -n "$PUBLIC_DNS_BIND_IP" ]]; then
  validate_value "public DNS bind IP" "$PUBLIC_DNS_BIND_IP" '^[A-Za-z0-9:._-]+$'
fi

if ! deployment_preset_modules "$DEPLOYMENT_PRESET" >/dev/null; then
  echo "Error: unknown preset: $DEPLOYMENT_PRESET" >&2
  echo "Hint: use simple-web, web-mail, web-mail-dns, or full-stack." >&2
  exit 1
fi

if [[ "$MODULES_SPECIFIED" -eq 0 ]]; then
  MODULES="$(deployment_preset_modules "$DEPLOYMENT_PRESET")"
fi

if [[ "$PROFILES_SPECIFIED" -eq 0 ]]; then
  PROFILES="$(deployment_preset_profiles "$DEPLOYMENT_PRESET")"
fi

if [[ -z "$ADMIN_ACCESS" ]]; then
  ADMIN_ACCESS="$(deployment_preset_admin_access "$DEPLOYMENT_PRESET")"
fi

if [[ -e "$OUTPUT_PATH" && "$FORCE" -ne 1 ]]; then
  echo "Error: output file already exists: $OUTPUT_PATH" >&2
  echo "Hint: pass --force to overwrite it, or choose --output /tmp/elektrine.env" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"

DB_PASSWORD="$(random_secret)"
ELEKTRINE_MASTER_SECRET="$(random_secret)$(random_secret)"
CADDY_EDGE_API_KEY="$(random_secret)$(random_secret)"

cat > "$OUTPUT_PATH" <<EOF
# Generated by scripts/deploy/generate_env.sh
# Docker self-hosting defaults. Prefer the small intent keys below; the deploy
# scripts derive lower-level Caddy/DNS values from them.

DEPLOYMENT_PRESET=$DEPLOYMENT_PRESET
ADMIN_ACCESS=$ADMIN_ACCESS
TLS_MODE=$TLS_MODE
PUBLIC_DNS_BIND_IP=$PUBLIC_DNS_BIND_IP

PRIMARY_DOMAIN=$PRIMARY_DOMAIN
PHX_HOST=$PRIMARY_DOMAIN
INSTANCE_DOMAIN=$PRIMARY_DOMAIN
SUPPORTED_DOMAINS=$PRIMARY_DOMAIN
PROFILE_BASE_DOMAINS=$PRIMARY_DOMAIN

PHX_SERVER=true
PORT=8080
# The generated Docker stack talks to the bundled Postgres service on a private
# Docker network. Leave TLS enabled for external DATABASE_URL deployments.
DATABASE_SSL_ENABLED=false

DB_PASSWORD=$DB_PASSWORD
ELEKTRINE_MASTER_SECRET=$ELEKTRINE_MASTER_SECRET

ELEKTRINE_ENABLED_MODULES=$MODULES
DOCKER_PROFILES="$PROFILES"
COMPOSE_PROJECT_NAME=docker

ACME_EMAIL=$ACME_EMAIL
CADDY_EDGE_API_KEY=$CADDY_EDGE_API_KEY
CADDY_ORIGIN_UPSTREAM=app:8080

# Derived automatically at deploy time:
# - ADMIN_ACCESS=netbird sets CADDY_ADMIN_HOST=admin.<domain> and requires
#   NETBIRD_ALLOWED_CIDRS with exact peer /32s.
# - PUBLIC_DNS_BIND_IP derives DNS_UDP_BIND and DNS_TCP_BIND.
# - TLS_MODE=external-wildcard or letsencrypt-dns selects the external-cert
#   Caddyfile.
#
# NETBIRD_ALLOWED_CIDRS="100.90.1.10/32 100.90.2.20/32"

# Uncomment to let docker_deploy.sh set Docker userland-proxy=false and restart
# Docker before deploy so bridged Caddy can preserve source IPs on Linux.
# ELEKTRINE_AUTO_CONFIGURE_DOCKER_SOURCE_IPS=true

# Keep uploads local for first boot. Enable Magpie/S3 later if you need it.
# S3_ACCESS_KEY_ID=
# S3_SECRET_ACCESS_KEY=
# S3_ENDPOINT=
# S3_BUCKET_NAME=
# S3_PUBLIC_URL=
# S3_SCHEME=http://
# S3_PORT=8090

# Wildcard TLS is opt-in. Leave these unset for first boot.
# CADDY_MANAGED_SITE_1="$PRIMARY_DOMAIN *.$PRIMARY_DOMAIN"
# CADDY_TLS_MOUNT_DIR=/opt/elektrine/certs
# CADDY_MANAGED_SITE_1_CERT_PATH=/opt/elektrine/certs/$PRIMARY_DOMAIN.fullchain.pem
# CADDY_MANAGED_SITE_1_KEY_PATH=/opt/elektrine/certs/$PRIMARY_DOMAIN.key.pem
# ACME_WILDCARD_RENEWAL_ENABLED=true

# Optional Magpie public media routing. Enable only with Magpie/S3.
# S3_PUBLIC_URL=https://media.$PRIMARY_DOMAIN
# CADDY_MEDIA_HOST=media.$PRIMARY_DOMAIN
# CADDY_MEDIA_UPSTREAM=magpie:8090
EOF

chmod 600 "$OUTPUT_PATH"
echo "Generated $OUTPUT_PATH"
echo "Next: scripts/deploy/doctor.sh --env-file $OUTPUT_PATH"
