#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_PATH="$ROOT_DIR/.env.production"
PRIMARY_DOMAIN=""
ACME_EMAIL=""
MODULES="chat,social,vault"
PROFILES="caddy"
FORCE=0

usage() {
  cat <<'EOF'
Usage: scripts/deploy/generate_env.sh --domain example.com --email admin@example.com [options]

Creates a minimal .env.production for first-run Docker self-hosting.

Options:
  --domain DOMAIN       Primary domain for the instance.
  --email EMAIL         ACME account email for Caddy-managed TLS.
  --modules LIST        Enabled modules. Default: chat,social,vault
  --profiles LIST       Docker profiles separated by spaces. Default: caddy
  --output PATH         Env file path. Default: .env.production
  --force               Overwrite an existing output file.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      PRIMARY_DOMAIN="$2"
      shift 2
      ;;
    --email)
      ACME_EMAIL="$2"
      shift 2
      ;;
    --modules)
      MODULES="$2"
      shift 2
      ;;
    --profiles)
      PROFILES="$2"
      shift 2
      ;;
    --output)
      OUTPUT_PATH="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    date +%s%N | sha256sum | cut -d ' ' -f 1
  fi
}

if [[ -z "$PRIMARY_DOMAIN" || -z "$ACME_EMAIL" ]]; then
  usage >&2
  exit 1
fi

if [[ -e "$OUTPUT_PATH" && "$FORCE" -ne 1 ]]; then
  echo "Error: output file already exists: $OUTPUT_PATH" >&2
  echo "Hint: pass --force to overwrite it, or choose --output /tmp/elektrine.env" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"

DB_PASSWORD="$(random_secret)"
ELEKTRINE_MASTER_SECRET="$(random_secret)$(random_secret)"
CADDY_EDGE_API_KEY="$(random_secret)$(random_secret)"

cat > "$OUTPUT_PATH" <<EOF
# Generated by scripts/deploy/generate_env.sh
# Minimal Docker self-hosting defaults. Add optional services only when needed.

PRIMARY_DOMAIN=$PRIMARY_DOMAIN
PHX_HOST=$PRIMARY_DOMAIN
INSTANCE_DOMAIN=$PRIMARY_DOMAIN
SUPPORTED_DOMAINS=$PRIMARY_DOMAIN
PROFILE_BASE_DOMAINS=$PRIMARY_DOMAIN

PHX_SERVER=true
PORT=8080
DATABASE_SSL_ENABLED=false

DB_PASSWORD=$DB_PASSWORD
ELEKTRINE_MASTER_SECRET=$ELEKTRINE_MASTER_SECRET

ELEKTRINE_ENABLED_MODULES=$MODULES
DOCKER_PROFILES=$PROFILES

ACME_EMAIL=$ACME_EMAIL
CADDY_EDGE_API_KEY=$CADDY_EDGE_API_KEY
CADDY_ORIGIN_UPSTREAM=app:8080

# Keep uploads local for first boot. Enable Magpie/S3 later if you need it.
# S3_ACCESS_KEY_ID=
# S3_SECRET_ACCESS_KEY=
# S3_ENDPOINT=
# S3_BUCKET_NAME=
# S3_PUBLIC_URL=
# S3_SCHEME=http://
# S3_PORT=8090

# Wildcard TLS is opt-in. Leave these unset for first boot.
# CADDY_MANAGED_SITE_1="$PRIMARY_DOMAIN *.$PRIMARY_DOMAIN"
# CADDY_TLS_MOUNT_DIR=/opt/elektrine/certs
# CADDY_MANAGED_SITE_1_CERT_PATH=/opt/elektrine/certs/$PRIMARY_DOMAIN.fullchain.pem
# CADDY_MANAGED_SITE_1_KEY_PATH=/opt/elektrine/certs/$PRIMARY_DOMAIN.key.pem
# ACME_WILDCARD_RENEWAL_ENABLED=true

# Optional Magpie public media routing. Enable only with Magpie/S3.
# S3_PUBLIC_URL=https://media.$PRIMARY_DOMAIN
# CADDY_MEDIA_HOST=media.$PRIMARY_DOMAIN
# CADDY_MEDIA_UPSTREAM=magpie:8090
EOF

chmod 600 "$OUTPUT_PATH"
echo "Generated $OUTPUT_PATH"
echo "Next: scripts/deploy/doctor.sh --env-file $OUTPUT_PATH"
