import Config

# Set environment for profile access control
config :elektrine, :environment, :dev

config :elektrine,
  enforce_https: false,
  allow_insecure_dav_jmap_auth: true,
  trusted_proxy_cidrs: ["127.0.0.1/32", "::1/128"]

dev_db_username =
  System.get_env("DB_USER") ||
    System.get_env("POSTGRES_USER") ||
    System.get_env("PGUSER") ||
    System.get_env("USER") ||
    "postgres"

dev_db_password =
  System.get_env("DB_PASSWORD") ||
    System.get_env("POSTGRES_PASSWORD") ||
    System.get_env("PGPASSWORD") ||
    ""

dev_db_hostname = System.get_env("DB_HOST") || System.get_env("PGHOST") || "localhost"
dev_db_name = System.get_env("DB_NAME") || System.get_env("PGDATABASE") || "elektrine_dev"

# Configure your database
config :elektrine, Elektrine.Repo,
  username: dev_db_username,
  password: dev_db_password,
  hostname: dev_db_hostname,
  database: dev_db_name,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :elektrine, ElektrineWeb.Endpoint,
  # Bind to 0.0.0.0 to expose the server to the docker host machine.
  # This makes make the service accessible from any network interface.
  # Change to `ip: {127, 0, 0, 1}` to allow access only from the server machine.
  http: [
    ip: {0, 0, 0, 0},
    port: 4000,
    http_1_options: [
      max_header_count: 50,
      max_header_length: 8_192
    ]
  ],
  check_origin: [
    "http://localhost:4000",
    "http://127.0.0.1:4000",
    "http://z.local:4000",
    "http://*.z.local:4000",
    "http://elektrine.local:4000"
  ],
  code_reloader: true,
  debug_errors: true,
  # Generate random secret for dev to avoid hardcoded secrets in repo
  secret_key_base:
    System.get_env("SECRET_KEY_BASE") ||
      Base.encode64(:crypto.strong_rand_bytes(48)),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:elektrine, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:elektrine, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :elektrine, ElektrineWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"apps/elektrine/priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"apps/elektrine/priv/gettext/.*(po)$",
      ~r"apps/elektrine_web/lib/elektrine_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :elektrine, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console,
  format: "[$level] $message\n",
  level: :info

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Disable Sentry in development
config :sentry, dsn: nil

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Configure Swoosh to use local file adapter for development
config :swoosh, :api_client, false

# Override mailer configuration to use local file adapter in development
# To use local file adapter instead of Postal API, set USE_LOCAL_EMAIL=true
if System.get_env("USE_LOCAL_EMAIL") == "true" do
  # Use local file adapter for testing
  IO.puts("Using local file adapter for emails")

  config :elektrine, Elektrine.Mailer,
    adapter: Swoosh.Adapters.Local,
    # We'll create this directory to store emails
    file_path: "tmp/emails",
    # Enable local preview in browser with
    # http://localhost:4000/dev/mailbox
    serve_endpoints: true
else
  # Use Postal API configuration from config.exs
end

# Use S3/R2 in development if configured, otherwise use local storage
if System.get_env("R2_ACCESS_KEY_ID") do
  config :elektrine, :uploads,
    adapter: :s3,
    bucket: System.get_env("R2_BUCKET_NAME") || "elektrine-uploads-dev",
    endpoint: System.get_env("R2_ENDPOINT"),
    # Optional: Custom domain for R2
    public_url: System.get_env("R2_PUBLIC_URL"),
    # Upload security limits
    max_file_size: 5 * 1024 * 1024,
    max_background_size: 10 * 1024 * 1024,
    max_image_width: 8192,
    max_image_height: 8192
else
  # Use local file storage when S3 credentials not configured
  config :elektrine, :uploads,
    adapter: :local,
    uploads_dir: "apps/elektrine/priv/static/uploads",
    max_file_size: 5 * 1024 * 1024,
    max_background_size: 10 * 1024 * 1024,
    max_image_width: 8192,
    max_image_height: 8192
end

# Configure ExAws for R2 in development:
config :ex_aws,
  access_key_id: System.get_env("R2_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("R2_SECRET_ACCESS_KEY"),
  region: "auto",
  json_codec: Jason,
  s3: [
    scheme: "https://",
    host: System.get_env("R2_ENDPOINT"),
    region: "auto",
    port: 443
  ]

# Cloudflare Turnstile test keys for development
config :elektrine, :turnstile,
  site_key: "1x00000000000000000000AA",
  secret_key: "1x0000000000000000000000000000000AA",
  verify_url: "https://challenges.cloudflare.com/turnstile/v0/siteverify",
  skip_verification: true
