import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :elektrine, ElektrineWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"
# SSL is handled by Fly.io proxy, no force_ssl needed

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Elektrine.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Configure JSON logging for production so cloud platforms (Fly.io) can parse log levels
config :logger, :console,
  format: {ElektrineWeb.JsonLogFormatter, :format},
  metadata: [:request_id, :user_id]

# Runtime production configuration, including reading
# of environment variables (including Sentry DSN), is done on config/runtime.exs.
